### ISSUE TITLE
会出现如下问题，请求原作者帮助：RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by CAuYi15** [ssg-research/WAFFLE#5]
我在进行跑python main.py --config_file configurations/baseline_experiments/mnist/1.ini --experiment training
就会出现如下错误，不确定是不是cuda版本问题，我用的是cuda10,ubuntu18.04，配置检查了多次
Traceback (most recent call last):
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 260, in handle_func_command
    cmd, args, kwargs, return_args_type=True
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 157, in hook_function_args
    new_args = hook_args(args)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 351, in <lambda>
    return lambda x: f(lambdas, x)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 559, in seven_fold
    lambdas[0](args[0], **kwargs),
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 329, in <lambda>
    else lambda i: forward_func[type(i)](i)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 56, in <lambda>
    else (_ for _ in ()).throw(PureTorchTensorFoundError),
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook_args.py", line 56, in <genexpr>
    else (_ for _ in ()).throw(PureTorchTensorFoundError),
syft.exceptions.PureTorchTensorFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 152, in <module>
    main(config, args.experiment, args.generate_watermark, args.patching_type)
  File "main.py", line 50, in main
    exp)
  File "main.py", line 69, in experiment_training
    federated_model, scores = agent.federated_train(log_interval=1000)
  File "/home/chenqianyi/WAFFLE-main/src/experiment.py", line 336, in federated_train
    output = client_model(data)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenqianyi/WAFFLE-main/src/Network.py", line 139, in forward
    out = self.block(x)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook.py", line 717, in overloaded_func
    response = TorchTensor.handle_func_command(command)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 270, in handle_func_command
    response = new_type.handle_func_command(new_command)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/pointers/object_pointer.py", line 88, in handle_func_command
    response = owner.send_command(location, command)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py", line 427, in send_command
    ret_val = self.send_msg(codes.MSGTYPE.CMD, message, location=recipient)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py", line 223, in send_msg
    bin_response = self._send_msg(bin_message, location)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/virtual.py", line 10, in _send_msg
    return location._recv_msg(message)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/virtual.py", line 13, in _recv_msg
    return self.recv_msg(message)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py", line 254, in recv_msg
    response = self._message_router[msg_type](contents)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/workers/base.py", line 385, in execute_command
    response = command(*args, **kwargs)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/hook/hook.py", line 717, in overloaded_func
    response = TorchTensor.handle_func_command(command)
  File "/home/chenqianyi/anaconda3/envs/pysyft/lib/python3.7/site-packages/syft/frameworks/torch/tensors/interpreters/native.py", line 287, in handle_func_command
    response = eval(cmd)(*args, **kwargs)
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

**Comment by bussfromspace** [comment]
CuDNN error usually happens when there is a mismatch between CuDNN, CUDA and the GPU (you can check here https://docs.nvidia.com/deploy/cuda-compatibility/index.html#binary-compatibility__table-toolkit-driver). Could you send me your python, torch, CUDA versions? 

Could you also try to reproduce the results again by setting
torch.backends.cudnn.enabled = False

**Comment by cherry-licongyi** [comment]
我也遇到这个问题，想问下楼主解决没？  I’M SUER the CuDNN, CUDA and the GPU is matched

**Comment by cherry-licongyi** [comment]
when setting
torch.backends.cudnn.enabled = False

it encounter ```RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'source' in call to _th_set_```

**Comment by bussfromspace** [comment]
Where do you exactly get this new error?
Usually these type of errors are ancountered when e.g., the model is in the CPU but the data is in GPU or vice versa. 

If it's the same place (in experiment.py, at line 336, output = client_model(data)), then it's likely that there is CPU GPU mismatch like I explained above.

**Comment by cherry-licongyi** [comment]
```
print(f"Data on GPU: {data.device}")
print(f"Target on GPU: {target.device}")
print(f"Model on GPU: {next(client_model.parameters()).device}")
```
![屏幕截图 2024-09-23 094645](https://github.com/user-attachments/assets/5d3cc4de-a079-4f2a-b722-a6f6988798dd)
![屏幕截图 2024-09-23 094735](https://github.com/user-attachments/assets/e9f9e7d7-cf6c-4ef1-aa93-0f99c8f6e79d)
